import { createSlice, PayloadAction } from '@reduxjs/toolkit'

// Define the initial state
import initialState from '../constants/initialState'

// Create a slice using createSlice
const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    incrementCounter: (state) => {
      state.value += 1
    },
    decrementCounter: (state) => {
      state.value -= 1
    },
    setCounter: (state, action: PayloadAction<number>) => {
      state.value = action.payload
    },
  },
})

// Export the actions generated by createSlice
export const { incrementCounter, decrementCounter, setCounter } =
  counterSlice.actions

// Export the reducer to be used in the store
export default counterSlice.reducer
