import { createSlice } from '@reduxjs/toolkit'
import {
  FETCH_USERS_ERROR,
  FETCH_USERS_SUCCESS,
  SET_PAGE,
} from '../types/userTypes'

// Initial state
import initialState from '../constants/initialState'

// Create a slice using createSlice
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    fetchUsersSuccess: (state, action: FETCH_USERS_SUCCESS) => {
      state.users = [...state.users, ...action.payload]
    },
    fetchUsersError: (state, action: FETCH_USERS_ERROR) => {
      state.error = action.payload
    },
    setPage: (state, action: SET_PAGE) => {
      state.page = action.payload
    },
  },
})

// Export actions generated by createSlice
export const { fetchUsersSuccess, fetchUsersError, setPage } = userSlice.actions

// Export the reducer to be used in the store
export default userSlice.reducer
